const plans={
1:{focus:'CHEST',ex:[['Chest Press','3 × 8–12'],['Incline Dumbbell Press','3 × 8–12'],['Cable Fly','2 × 12–15']]},
2:{focus:'BACK',ex:[['Lat Pulldown','3 × 8–12'],['Seated Cable Row','3 × 8–12'],['Chest-Supported Row','2 × 10–12']]},
3:{focus:'LEGS',ex:[['Leg Press','3 × 8–12'],['Leg Curl','3 × 10–15'],['Leg Extension','2 × 10–15'],['Calf Raises','3 × 12–15']]},
4:{focus:'SHOULDERS',ex:[['Shoulder Press','3 × 8–12'],['Lateral Raises','3 × 12–15'],['Reverse Fly','3 × 12–15']]},
5:{focus:'ARMS',ex:[['Dumbbell Curl','3 × 8–12'],['Hammer Curl','2 × 10–12'],['Triceps Pushdown','3 × 8–12'],['Overhead Triceps Extension','2 × 10–12']]}}
const S=JSON.parse(localStorage.getItem('system-v1')||'null')||{level:1,checkpoint:0,stats:{STR:0,STA:0,MND:0,WIL:0,FOC:0,DIS:0},sick:false,logs:{}};
const save=()=>localStorage.setItem('system-v1',JSON.stringify(S));
function requirements(l){let steps=l<=5?3000:l<=10?4000:l<=15?5000:l<=20?6000:l<=25?7000:l<=30?8000:l<=35?9000:10000;let read=l<=5?15:l<=10?20:l<=15?25:30;return{steps,read,trading:l>=21?60:0}}
function currentPlan(){let d=((S.level-1)%5)+1;return plans[d]}
function render(){document.body.classList.toggle('sick',S.sick);let l=S.level,r=requirements(l),p=currentPlan(),blockStart=Math.floor((l-1)/5)*5+1,day=(l-blockStart)+1;level.textContent=l;phase.textContent=l<=60?'BUILD THE SYSTEM':'LIVE THE SYSTEM';blockProgress.style.width=((day-1)/5*100)+'%';checkpoint.textContent=`Checkpoint LV${S.checkpoint} · Block ${blockStart}–${Math.min(blockStart+4,365)}`;dayTitle.textContent=`LV${l} · ${p.focus}`;modeBtn.textContent=S.sick?'SICK MODE ON':'SICK / INJURY';stats.innerHTML=Object.entries(S.stats).map(([k,v])=>`<div class=stat><small>${k}</small><b>${v}</b></div>`).join('');let log=S.logs[l]||{};quests.innerHTML=`<label class=quest><input type=checkbox data-q=str ${log.str?'checked':''}><span><b>Strength · ${p.focus}</b><small>Complete today's training</small></span></label><label class=quest><input type=checkbox data-q=steps ${log.steps?'checked':''}><span><b>${r.steps.toLocaleString()} steps</b><small>STA main quest</small></span></label><label class=quest><input type=checkbox data-q=read ${log.read?'checked':''}><span><b>${r.read} min physical book</b><small>MND main quest · physical book only</small></span></label>${r.trading?`<label class=quest><input type=checkbox data-q=trading ${log.trading?'checked':''}><span><b>${r.trading} min Trading Study</b><small>New strategies, ideas or structured learning</small></span></label>`:''}`;workout.innerHTML=p.ex.map((x,i)=>`<div class=exercise><b>${x[0]} · ${x[1]}</b><div class=sets><input data-ex='${i}-kg' placeholder='kg / load' value='${log['e'+i+'kg']||''}'><input data-ex='${i}-reps' placeholder='reps / notes' value='${log['e'+i+'reps']||''}'></div></div>`).join('');sleep.value=log.sleep||'';nutrition.checked=!!log.nutrition;document.querySelectorAll('[data-q]').forEach(e=>e.onchange=()=>{S.logs[l]=S.logs[l]||{};S.logs[l][e.dataset.q]=e.checked;save()});document.querySelectorAll('[data-ex]').forEach(e=>e.onchange=()=>{S.logs[l]=S.logs[l]||{};let [i,t]=e.dataset.ex.split('-');S.logs[l]['e'+i+t]=e.value;save()})}
modeBtn.onclick=()=>{S.sick=!S.sick;save();render()};sleep.onchange=()=>{S.logs[S.level]=S.logs[S.level]||{};S.logs[S.level].sleep=sleep.value;save()};nutrition.onchange=()=>{S.logs[S.level]=S.logs[S.level]||{};S.logs[S.level].nutrition=nutrition.checked;save()};
completeDay.onclick=()=>{if(S.sick){alert('Sick / Injury Mode is active. Progression is protected.');return}let r=requirements(S.level),log=S.logs[S.level]||{},needed=['str','steps','read'].concat(r.trading?['trading']:[]);if(!needed.every(k=>log[k])){alert('Complete all Main Quests first. Bonus quests do not block progression.');return}S.stats.STR++;S.stats.STA++;S.stats.MND++;S.stats.DIS++;if(S.level%5===0){S.checkpoint=S.level;alert(`BLOCK COMPLETE — LV${S.level}. Dungeon / Recovery flow will be added in the next build.`)}if(S.level<365)S.level++;save();render()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();
